# -*- coding: utf-8 -*-
"""Copia de prueba_trabajo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jigqGqx6_dHmULSJOssYinGZZVmT-0GE
"""

def highestValuePalindrome(n,k,s):
  cadenaLista=list(s)
  cadena2=[]
  numero='1'+'0'*n

  #Agregamos todas las combinaciones de números a la cadena
  for a in range(0,int(numero)):

    cadena2.append(str(a).zfill(n))

  #Revertimos la cadena para poder comparar si es palindromo
  cadena3=[]
  for b in range(0,int(numero)):
    cadena3.append(cadena2[b][::-1])

  #Revisamos si es palindromo y si se cumple el cambio de números
  cadenaFinal='-1'
  for b in range(0,int(numero)):
 
    if cadena2[b]==cadena3[b]: #revisa si el número es palindromo
      cont=0
    
      for c in range(0,n):
     
        if cadena2[b][c]!=cadenaLista[c]:# si lo es revisa cuantos valores cambiaron en comparación con el inicial
          cont=cont+1
    
      if cont==k:#revisa si los valores cambiaron el número de veces que debia ser
        cadenaFinal=cadena2[b]
  
  return cadenaFinal

s='092282'
n=len(s)
k=3;

print(highestValuePalindrome(n,k,s))